import { StyleSheet } from "react-native";
import { colors } from "@/assets/styles/constants";

export const mobilePlayerStyles = StyleSheet.create({
  contentContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    minWidth: "100%",
    minHeight: "100%",
    overflow: "hidden",
    backgroundColor: colors.surface.splash,
  },
  innerShadow: {
    position: "absolute",
    top: -10,
    bottom: -10,
    left: -10,
    right: -10,
    borderRadius: 12,
    zIndex: 4,
  },
  blurBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
  },
  touchOverlay: {
    flex: 1,
    zIndex: 4,
    minWidth: "100%",
    minHeight: "100%",
    position: "absolute",
    top: 0,
    left: 0,
  },
  video: {
    width: "100%",
    height: "100%",
    flex: 1,
    zIndex: 3,
  },
  controlsContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 50,
    zIndex: 6,
    paddingHorizontal: 18,
  },
  topPanelPressable: {
    position: "absolute",
    top: 24,
    right: 20,
    left: 20,
    height: 48,
    zIndex: 9,
  },
  topPanel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    width: "100%",
    height: "100%",
    zIndex: 10,
  },
  topPanelPart: {
    flexDirection: "row",
    gap: 16,
  },
  topPanelButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  centerPanel: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    position: "absolute",
    margin: "auto",
    zIndex: 10,
  },
  rewindButton: {
    position: "relative",
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
  },
  playButton: {
    position: "relative",
    width: 96,
    height: 96,
    alignItems: "center",
    justifyContent: "center",
  },
  infoPanel: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 8,
    width: "100%",
    minHeight: 45,
    paddingHorizontal: 14,
  },
  slider: {
    zIndex: 5,
    paddingTop: 12,
    width: "100%",
    paddingHorizontal: 0,
    marginHorizontal: 0,
  },
  timePanel: {
    minWidth: 112,
  },
  title: {
    fontFamily: "Poppins-SemiBold",
    color: colors.text.body,
    fontSize: 20,
  },
  subTitle: {
    fontFamily: "Poppins-Regular",
    color: colors.neutral.gray400,
    fontSize: 14,
  },
  skipButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 15,
    overflow: "hidden",
  },
  skipText: {
    fontFamily: "Poppins-MediumItalic",
    color: colors.text.body,
    fontSize: 14,
    textTransform: "uppercase",
  },
  time: {
    fontFamily: "HelveticaNow-Medium",
    color: colors.text.body,
    textAlign: "right",
    fontSize: 14,
  },
  blur: {
    position: "absolute",
    borderRadius: 50,
    overflow: "hidden",
    zIndex: -2,
    top: 1,
    left: 1,
    right: 1,
    bottom: 1,
  },
});
