import { palette } from "./palette";
import { withAlpha } from "./color-utils";

export const colors = {
  text: {
    body: palette.neutral.mint,
    accent: palette.brand.lime,
    onLight: palette.neutral.gray950,
    muted: palette.neutral.gray500,
    inverse: palette.neutral.white,
    error: palette.status.error,
  },
  surface: {
    app: palette.neutral.gray950,
    card: palette.neutral.gray850,
    cardMuted: palette.neutral.gray825,
    elevated: palette.neutral.gray775,
    muted: palette.neutral.gray800b,
    input: palette.neutral.mint,
    button: palette.neutral.gray750,
    sidebar: palette.neutral.gray625,
    splash: palette.neutral.gray975,
    box: palette.neutral.gray600b,
    deep: palette.neutral.gray575,
    alt: palette.neutral.gray675,
    overlay: palette.neutral.black,
  },
  border: {
    default: palette.neutral.gray725,
    subtle: withAlpha(palette.neutral.mint, 0.25),
    onCard: palette.neutral.gray650,
    focus: palette.brand.lime,
  },
  brand: {
    blue: palette.brand.blue,
  },
  action: {
    primary: palette.brand.lime,
    primaryMuted: palette.brand.limeSoft,
    secondary: palette.neutral.gray750,
    secondaryPressed: palette.neutral.gray700b,
    tabHighlight: withAlpha(palette.neutral.white, 0.5),
    tabBorder: withAlpha(palette.neutral.white, 0.2),
  },
  accent: {
    challenge: palette.brand.limeSoft,
    highlight: palette.brand.limeBright,
  },
  state: {
    error: palette.status.error,
    success: palette.status.success,
    successBright: palette.status.successBright,
    progress: palette.status.progress,
    info: palette.status.info,
    warning: palette.status.warning,
    selection: palette.status.selection,
    orange: palette.status.orange,
    orangeDeep: palette.status.orangeDeep,
    orangeAccent: palette.status.orangeAccent,
    destructive: palette.status.destructive,
  },
  input: {
    background: palette.neutral.mint,
    text: palette.neutral.gray950,
    placeholder: palette.neutral.gray950,
    placeholderMuted: withAlpha(palette.neutral.gray950, 0.5),
    outline: palette.neutral.mint,
    cursor: palette.status.selection,
  },
  overlay: {
    scrim: withAlpha(palette.neutral.black, 0.5),
    scrimHeavy: withAlpha(palette.neutral.black, 0.78),
    gradient: palette.neutral.gray550,
  },
  neutral: {
    gray100: palette.neutral.gray50,
    gray200: palette.neutral.gray200,
    gray300: palette.neutral.gray300,
    gray400: palette.neutral.gray400,
    gray500: palette.neutral.gray500,
    gray600: palette.neutral.gray600,
    gray700: palette.neutral.gray700,
    gray800: palette.neutral.gray800,
    gray900: palette.neutral.gray900,
    grayaaa: palette.neutral.grayaaa,
    divider: palette.neutral.divider,
  },
  alpha: {
    white20: withAlpha(palette.neutral.white, 0.2),
    black25: withAlpha(palette.neutral.black, 0.25),
    black40: withAlpha(palette.neutral.black, 0.4),
    black50: withAlpha(palette.neutral.black, 0.5),
    divider20: withAlpha(palette.neutral.divider, 0.2),
    divider40: withAlpha(palette.neutral.divider, 0.4),
    transparent: "#FFFFFF00",
  },
  decorative: palette.decorative,
} as const;
