import * as Font from "expo-font";

export default async function fontsLoader() {
  await Font.loadAsync({
    "HelveticaNow-Black": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-Black.ttf"),
    "HelveticaNow-BlackIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-BlackIta.ttf"),
    "HelveticaNow-Bold": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-Bold.ttf"),
    "HelveticaNow-BoldIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-BoldIta.ttf"),
    "HelveticaNow-ExtBdIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-ExtBdIta.ttf"),
    "HelveticaNow-ExtBlk": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-ExtBlk.ttf"),
    "HelveticaNow-ExtraBlackItalic": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-ExtBlkIta.ttf"),
    "HelveticaNow-ExtLt": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-ExtLt.ttf"),
    "HelveticaNow-ExtLtIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-ExtLtIta.ttf"),
    "HelveticaNow-ExtraBold": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-ExtraBold.ttf"),
    "HelveticaNow-Hairline": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-Hairline.ttf"),
    "HelveticaNow-HairlineI": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-HairlineI.ttf"),
    "HelveticaNow-Light": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-Light.ttf"),
    "HelveticaNow-LightIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-LightIta.ttf"),
    "HelveticaNow-MedIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-MedIta.ttf"),
    "HelveticaNow-Medium": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-Medium.ttf"),
    "HelveticaNow-RegIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-RegIta.ttf"),
    "HelveticaNow-Regular": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-Regular.ttf"),
    "HelveticaNow-Thin": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-Thin.ttf"),
    "HelveticaNow-ThinIta": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-ThinIta.ttf"),
    "HelveticaNow-XBold": require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay-XBold.otf"),
    HelveticaNow: require("@fonts/HelveticaNowDisplay/HelveticaNowDisplay.otf"),
    "NeueBit-Bold": require("@fonts/NeueBit/NeueBit-Bold.ttf"),
    "Zeit-LightItalic": require("@fonts/Zeit/Zeit-LightItalic.otf"),
    "Poppins-Black": require("@fonts/Poppins/Poppins-Black.ttf"),
    "Poppins-BlackItalic": require("@fonts/Poppins/Poppins-BlackItalic.ttf"),
    "Poppins-Bold": require("@fonts/Poppins/Poppins-Bold.ttf"),
    "Poppins-BoldItalic": require("@fonts/Poppins/Poppins-BoldItalic.ttf"),
    "Poppins-ExtraBold": require("@fonts/Poppins/Poppins-ExtraBold.ttf"),
    "Poppins-ExtraBoldItalic": require("@fonts/Poppins/Poppins-ExtraBoldItalic.ttf"),
    "Poppins-ExtraLight": require("@fonts/Poppins/Poppins-ExtraLight.ttf"),
    "Poppins-ExtraLightItalic": require("@fonts/Poppins/Poppins-ExtraLightItalic.ttf"),
    "Poppins-Italic": require("@fonts/Poppins/Poppins-Italic.ttf"),
    "Poppins-Light": require("@fonts/Poppins/Poppins-Light.ttf"),
    "Poppins-LightItalic": require("@fonts/Poppins/Poppins-LightItalic.ttf"),
    "Poppins-Medium": require("@fonts/Poppins/Poppins-Medium.ttf"),
    "Poppins-MediumItalic": require("@fonts/Poppins/Poppins-MediumItalic.ttf"),
    "Poppins-Regular": require("@fonts/Poppins/Poppins-Regular.ttf"),
    "Poppins-SemiBold": require("@fonts/Poppins/Poppins-SemiBold.ttf"),
    "Poppins-SemiBoldItalic": require("@fonts/Poppins/Poppins-SemiBoldItalic.ttf"),
    "Poppins-Thin": require("@fonts/Poppins/Poppins-Thin.ttf"),
    "Poppins-ThinItalic": require("@fonts/Poppins/Poppins-ThinItalic.ttf"),
  });
}
